name: flutter_api_discovery
description: A flutter app to train on using APIs with dart, through a public API from SNCF, about lost objects in train stations.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  http: ^1.2.2
  sqflite: ^2.4.0
  crypto: ^3.0.6
  flutter_launcher_icons: ^0.14.1

flutter_icons:
  android: "launcher_icon"
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true
  assets:
      - assets/logo.png
